//describe your actionTypes here

export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const GET_TAGS_REQUEST = "GET_TAGS_REQUEST";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAILURE = "GET_TAGS_FAILURE";

export const ADD_TAGS_REQUEST = "ADD_TAGS_REQUEST";
export const ADD_TAGS_SUCCESS = "ADD_TAGS_SUCCESS";
export const ADD_TAGS_FAILURE = "ADD_TAGS_FAILURE";

export const ADD_SUBTASKS_REQUEST = "ADD_SUBTASKS_REQUEST";
export const ADD_SUBTASKS_SUCCESS = "ADD_SUBTASKS_SUCCESS";
export const ADD_SUBTASKS_FAILURE = "ADD_SUBTASKS_FAILURE";

export const DELETE_SUBTASKS_REQUEST = "DELETE_SUBTASKS_REQUEST";
export const DELETE_SUBTASKS_SUCCESS = "DELETE_SUBTASKS_SUCCESS";
export const DELETE_SUBTASKS_FAILURE = "DELETE_SUBTASKS_FAILURE";

export const UPDATE_SUBTASKS_REQUEST = "UPDATE_SUBTASKS_REQUEST";
export const UPDATE_SUBTASKS_SUCCESS = "UPDATE_SUBTASKS_SUCCESS";
export const UPDATE_SUBTASKS_FAILURE = "UPDATE_SUBTASKS_FAILURE";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";


export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const ADD_EVENTS_REQUEST = "ADD_EVENTS_REQUEST";
export const ADD_EVENTS_SUCCESS = "ADD_EVENTS_SUCCESS";
export const ADD_EVENTS_FAILURE = "ADD_EVENTS_FAILURE";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const GET_CHECKPOINT_REQUEST = "GET_CHECKPOINT_REQUEST";
export const GET_CHECKPOINT_SUCCESS = "GET_CHECKPOINT_SUCCESS";
export const GET_CHECKPOINT_FAILURE = "GET_CHECKPOINT_FAILURE";


export const ADD_CHECKPOINT_REQUEST = "ADD_CHECKPOINT_REQUEST";
export const ADD_CHECKPOINT_SUCCESS = "ADD_CHECKPOINT_SUCCESS";
export const ADD_CHECKPOINT_FAILURE = "ADD_CHECKPOINT_FAILURE";


export const UPDATE_CHECKPOINT_REQUEST = "UPDATE_CHECKPOINT_REQUEST";
export const UPDATE_CHECKPOINT_SUCCESS = "UPDATE_CHECKPOINT_SUCCESS";
export const UPDATE_CHECKPOINT_FAILURE = "UPDATE_CHECKPOINT_FAILURE";


